FROM python:3.8.13 as base

# Install system dependencies
RUN apt-get update && \
    apt-get install -y libhdf5-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ADD requirements.txt .

# Upgrade pip and install Python dependencies
RUN HDF5_DIR=/usr/lib/aarch64-linux-gnu/hdf5/serial/ \
    pip install -r requirements.txt

ENV PYTHONPATH=$PYTHONPATH:/src/

COPY ./ /src/

WORKDIR /src

FROM base as test
RUN ["pytest", "-v", "/src/tests"]

FROM base as build
ENTRYPOINT ["python3", "/src/ml_service.py"]

