version: '3.8'

services:
  postgres: # We can choose which name to put here
    image: postgres 
    container_name: ml_app_postgres # Name of the container
    environment: # Environment variables (could also be in a .env)
      - POSTGRES_USER=anyone_ai
      - POSTGRES_PASSWORD=anyone_ai
      - POSTGRES_DB=ml_app
    ports:
      - "5432:5432" # local port:container port
    volumes:
      - pgdata:/var/lib/postgresql/data # Where to save all data for this service

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379" # One for database
      - "8001:8001" # One for message broker

  ml_app:
    build:
      context: ./ml_api # Root path where the Dockerfile is located
      dockerfile: Dockerfile # Name of the Dockerfile (custom service, not a base one)
    depends_on:
      - postgres
      - redis
      - model_service
    ports:
      - "8000:8000"

  model_service:
    build:
      context: ./model_service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      
volumes:
  pgdata: